### ISSUE TITLE
Add options menu and install process as gif.

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#13]
How about showing the options menu as well as install process as an animated gif in the readme?

**Comment by PhilippSalvisberg** [comment]
In fact I'd like to replace the existing GIF with a video, since I find GIFs a bit disturbing. So yes, having videos for demonstrating

a) the install process
b) the adaption of utPLSQL preferences

would be a good idea. But I would like to create a ReadMe with 3 concurrently playing GIFs...

**Comment by PhilippSalvisberg** [comment]
@jgebal I've changed the [README.md](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/blob/master/README.md) to show a PNG and call the animated GIF via link. This is better, but not good, since it is not possible to navigate within the animated GIF.

An alternative is to use a video. Unfortunately using a plain link to a video hosted on GitHub leads to a download. Embedding videos is not supported in Markdown which leaves two options:

a) call a Youtube URL, e.g. https://www.youtube.com/watch?v=uGs6Uoj-EqM 
b) call an URL hosted on uplsql.org or similar where the video may be embedded without all the other stuff you get when calling the Youtube website (ads, autoplay, ...)

Suggestions?

**Comment by jgebal** [comment]
It would be best to have self-hosted video but youtube will be a good-enough option for now I think.

For self-hosted option we have utplsql.org (generated from githubpages) and for utPLSQL/utPLSQL we generate documentation sub-pages.
It's far from good but it must be good-enough for now as we didn't have time to spend on the layout and format of the page itself.
We could have gh-pages branch for sqlDeveloper plugin, and keep the video(s) there.
Then we could probably embed it in the generated content for pages.

**Comment by PhilippSalvisberg** [comment]
I agree that the self-hosted option is probably the best. In the meantime I use endless-looping animated GIFs.
