### ISSUE TITLE
Test result window not showing up

### ISSUE THREAD

**Issue by NicoleRiedel** [utPLSQL/utPLSQL-SQLDeveloper#139]
With SQL Developer version 21.4.0.346 I can run unit tests but the test result window does not show up. This was working fine with SQL Developer version 20.4.1.407.

When I select option "Run utPLSQL test" the context menu disappears after a short time and nothing more happens. In the statements log I can see that the unit tests are started. But I cannot see the results.

When I select option "Code coverage ..." I can do the configuration for the schema and the packages to be covered. After clicking on the Run button the popup window disappears. After some time the browser is opened to show the html with the results of the code coverage. Obviously tests are executed. But the UI part for viewing the results is missing.

I have attached a picture of the window that I am missing in the higher SQL Developer version.

![image](https://user-images.githubusercontent.com/97105008/148067846-cd7d2342-c901-43b3-997a-c23ecfd892d9.png)

**Comment by PhilippSalvisberg** [comment]
In my environments the test runner is visible in SQLDev 21.4.0/.1. I've tested it on Windows and macOS using JDK 11 (since JDK 8 has various issues in these two versions). However, I do not think this is JDK related. I'd try to from the Windows menu:

Reset Windows To Factory Settings

Please let me know if this helped.

**Comment by NicoleRiedel** [comment]
I’m sorry that I forgot to mention that I’m working with Windows 10. JDK wasn’t installed at all. Nevertheless, the test runner is visible for the SQL Developer 20.4.1.
Now I have installed JDK 8 (JDK 11 is not available for me). But this doesn’t solve the problem. I even rebooted my machine.

My colleagues don’t have problems with SQL Developer 21.4.0. The test runner is showing for them. If at all they should have also installed JDK 8. Just one other colleague has the problem that the test runner is not always coming. Sometimes it comes but sometimes not. But so far he could not figure out what might cause the test runner not to show up.

**Comment by PhilippSalvisberg** [comment]
> Now I have installed JDK 8 (JDK 11 is not available for me). But this doesn’t solve the problem. I even rebooted my machine.

This confirms my suspicion that your issue is not JDK related.

>I'd try to run from the Windows menu:
>Reset Windows To Factory Settings

Have you tried that?

**Comment by NicoleRiedel** [comment]
No, I haven’t tried that because I am not aware of the consequences. What exactly will be reset? I don’t want to take the risk of being unable to connect with the internet or to my company’s network.

**Comment by PhilippSalvisberg** [comment]
>>>I'd try to run from the Windows menu:
>>>Reset Windows To Factory Settings

>>Have you tried that?

>No, I haven’t tried that because I am not aware of the consequences. What exactly will be reset? I don’t want to take the risk of being unable to connect with the internet or to my company’s network.

It resets all windows (their positions and their visibility such as Reports Connections, Snippets, Files, Code Outline, Log etc.) to factory settings. It leaves the existing connections as is. It usually fixes the issues you are describing where a window stays invisible. Windows with their associated classes are serialized and persisted when you closes SQLDev. Reloading these classes may fail when a class is incompatible and that is not handled properly. This usually happens when you update SQLDev or extensions. In any case it is a software bug (somewhere), but difficult to identify and to reproduce.

Please do that and let me know if "Reset Windows To Factory Settings" helped. Thx.

**Comment by NicoleRiedel** [comment]
Sorry, I completely misunderstood you. I assumed that the reset has to be done on OS level and hence my fears. I did not see that within SQL Developer I have to open the Window menu and then select option “Reset Windows To Factory Settings” (although you clearly stated that).

Now I have done this. And now it works. 😊

Thanks for your support. You can close the issue.

**Comment by PhilippSalvisberg** [comment]
No problem. Thanks for reporting back.
