### ISSUE TITLE
Run utPLSQL tests option disabled in SQL Developer

### ISSUE THREAD

**Issue by itguyforautomation** [utPLSQL/utPLSQL-SQLDeveloper#21]
utPLSQL version: v3.0.4.1372
utPLSQL-SQLDeveloper plugin Version: 0.2.1
Database Version: Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit

Problem:
“Run utPLSQL test” option went disabled

Troubleshooting:
1. Uninstall, and install the utplsql plugin, and restart SQL Developer tool.
2. Uninstall, and install the SQL Developer tool & utplsql plugin, and restart SQL Developer tool.

But the problem still persists. Can you help us with necessary steps to fix the issue?

![image](https://user-images.githubusercontent.com/39102994/39782282-b8480e20-52df-11e8-9f2f-e9a35a129517.png)
# #

**Comment by PhilippSalvisberg** [comment]
Does you connection name contain spaces? If yes, then you are hiitting bug [16](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/issues/16). This is bug is fixed in the [current snapshot version](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/releases/tag/v0.3.0-SNAPSHOT). I suggest to use this version.

**Comment by itguyforautomation** [comment]
It works now after using latest version 0.3.0 snapshot 

Thanks

**Comment by PhilippSalvisberg** [comment]
Thank you for the confirmation. I close this issue.
