### ISSUE TITLE
Can we have utPLSQL Icon in navigator menu?

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#3]
I love the icon that shows in the code editor menu.
Can we have a similar icon in the navigator menu?

**Comment by PhilippSalvisberg** [comment]
Me too. In fact I've tried to assign the utPLSQL.png, but failed. Based on my analysis it is not possible with the current implementation approach, using the "sqldev-action-hook" to extend the navigator menu. It is possible to define icons in the related related XML configuration (navigator_actions.xml in this case), but the icon must be visible to resource loader. This means I can use standard Oracle icons but not mine, since the Oracle extension implementing the navigator has not been given access to the utplsql extension and its resources. The hook for the PL/SQL editor is implemented differently. In this case it is possible to provide a own resource loader and therefore use own icons in the context menu. 

Maybe there is a way to extend the navigator programatically, without XML configurations. It needs for sure more research before I can finally answer your question.

**Comment by PhilippSalvisberg** [comment]
@krisrice suggested via twitter the following:

```
<item ….>..
<iconName>/org/utplsql/sqldev/resources/images/utPLSQL.png</iconName>
</item>
```

I've tried that and and worked!
