### ISSUE TITLE
ut3 schema hardcoded in oddgen report

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#42]
The oddgen doesnt show unit tests if utplsql is installed into diffeent schema than ut3

**Comment by PhilippSalvisberg** [comment]
Yep. The only place where the schema is hard-coded (beside tests), is [here](https://github.com/utPLSQL/utPLSQL-SQLDeveloper/blob/02cfa2f08a4ca62eacd30e6f99615d4f5090465d/sqldev/src/main/java/org/utplsql/sqldev/dal/UtplsqlDao.xtend#L291).  

The reason was, that utPLSQL does not expose `ut_annotation_manager`. It is not part of the API. Hence no public synonym available. But without the annotation manager the extension is almost helpless.

Any suggestions?

**Comment by PhilippSalvisberg** [comment]
Actually, I have a way to find the installed schema (`get_UtplsqlSchema`). I should have used that in this query as well. I can fix that.

Using non-API packages is another issue.
