### ISSUE TITLE
Coverage on another schema objects

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL-SQLDeveloper#63]
There are following issues:

# Include objects not populated when selecting Other user
When opening a Code coverage report window by navigating: Connection->Other Users->Some User->Packages->UT_package->Right click (Code coverage), the field `Include objects` is not getting populated. 

**Expected behavior**

`Include objects` gets populated the same way as it is when navigating: Connection->Packages->UT_package->Right click (Code coverage)

# The objects on Include objects list re not prefixed with owner

When tests are located in different schema then the tested code, the populated `Include objects` list does not give expected results - no coverage is showing.

The objects need to be prefixed with schema name.

**Below animation illustrates both issues as well as the correct outcomes**

![SQLDev-coverage_issue](https://user-images.githubusercontent.com/1398171/60687960-20986d00-9eaa-11e9-9e62-30a490a031f8.gif)

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue.

Populating default values for `include objects` is currently supported only for tests suites owned by connected user. It's a good idea to support that as well users listed below the `Other Users` node. 

In your case you can connect to `ut3_tester` and run code coverage from there, entering `UT3` for schema under test. As you shown, it does not work. The reason is, that `ut3_tester` lacks the necessary privileges to produce a code coverage result for the  `UT3` schema. As soon as you grant the necessary privileges (e.g. the `DBA` role or something more sensible) this works. I agree that it we should simplify the usage of code coverage and prefix all include objects by its owner. Then `Schema unter test` could be left empty.
