### ISSUE TITLE
"Run utPLSQL test" is not showing up in sql developer tool menu option 

### ISSUE THREAD

**Issue by itguyforautomation** [utPLSQL/utPLSQL-SQLDeveloper#96]
OS: MacOS Mojave 10.14.6
Database Version: "Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.6.0.0.0"
SQL Developer Version: 19.2.1.247\
utPLSQL Version: v3.1.10.3349
utPLSQL-SQL Developer extension Version : v1.1.1

Executed Headless installation to install utPLSQL on oracle database.
Installed sql developer tool
Installed utplsql-sql developer extension without any issues but it's not showing up "Run utPLSQL test" in the menu option 

**This is how I installed utPLQL-SQL developer extension;**

In SQL Developer - Help - Check for Updates
I install from local files --> utplsql_for_SQLDev_1.1.1.zip

New Installs: Database - utPLSQL for SQL Developer
press Finish
![image](https://user-images.githubusercontent.com/39102994/78399633-42eb2280-75c3-11ea-9520-d0554a5f7998.png)

To finish installing updates, SQL Developer needs to restart.
Do you want to restart now? --> Yes
 
How to install utPLSQL for SQL Developer?
Can I provide more information?

**Comment by PhilippSalvisberg** [comment]
When you select `Tools` -> `Feature` from the main menu, you should see something like this in the `Installed Updates` tab:

![image](https://user-images.githubusercontent.com/3883171/78406721-81a0cd00-7603-11ea-8f2e-a4173869a130.png)

If `utPLSQL for SQL Developer` is missing then something went wrong during the installation of the extension. In this case I suggest to try it again and post every message you get during the installation process.

If the extension is installed, then please select `Help` -> `About` from the main menu and query for `utPLSQL` in the extensions tab. You should see the following:

![image](https://user-images.githubusercontent.com/3883171/78406937-04c22300-7604-11ea-8ff2-154a68a65b67.png)

The status should be `fully loaded`.  

Please check also the extensions log via `View` -> `Extensions Diagnostics`. It's expected to be empty 

![image](https://user-images.githubusercontent.com/3883171/78407663-a5651280-7605-11ea-837f-f57c6988c9a2.png)

If not, please post the content of this window. 

Thank you.

**Comment by itguyforautomation** [comment]
Hi Philip, Thanks for your response.

utPLSQL for SQL Developer is missing under `Tools` -> `Feature` -> `Installed Updates` tab

![image](https://user-images.githubusercontent.com/39102994/78411004-30c9ae00-75dc-11ea-8851-c9a47c11fe22.png)

utPLSQL is missing under `Help` -> `About`

Here's how I installed attaching screenshots;

Step#1:
In SQL Developer -` Help - Check for Updates` -->`install from local files `--> utplsql_for_SQLDev_1.1.1.zip

![image](https://user-images.githubusercontent.com/39102994/78410643-f14e9200-75da-11ea-83d6-a12e19beeac7.png)

Step#2:
Click "`Next`" --> Click "`Finish`"

![image](https://user-images.githubusercontent.com/39102994/78410741-34a90080-75db-11ea-9074-9201e55996ea.png)

Step#3:
`Do you want to restart now?` `Yes`
![image](https://user-images.githubusercontent.com/39102994/78410772-60c48180-75db-11ea-9ecd-35b80f6a6689.png)


Did I miss any step? Please provide me more information

**Comment by PhilippSalvisberg** [comment]
This sounds similar to an issue I blogged about [here](https://www.salvis.com/blog/2015/05/05/cannot-install-extensions-in-sql-developer-4-on-mac-os-x/). But you did not mention the "Some updates have already been installed since SQL Developer was started" message. 

However, It looks like something went wrong during the internal JDeveloper/SQL Developer installation procedure. I assume that you find the following file `$TMPDIR/$USER/jdeveloper-deferred-updates.txt` and a directory named 
`/usr/$USER/.sqldeveloper/tmp` containing files created during the installation procedure. This is an indication that something went wrong. 

It looks like that your environment (user rights, Java version, ...) leads to errors during Oracle SQL Developer extensions installations. I assume you cannot install any SQL Developer extension. You may [try Show Me Password](https://github.com/tomecode/show-me-password-sqldev-jdev). **Can Please confirm that?** 

I created an additional, standard user (uid 502, no adminstrator rights) on my macBook and I installed a dedicated SQL Developer app, owned by this user. And in this setup I cannot install any SQL Developer extension as well. Does not matter if I use JDK8 oder JDK11. Strange.

Do you use a user with a uid different to 501 (open a terminal and type `id` to find out)?

**Comment by PhilippSalvisberg** [comment]
I found a workaround for installing SQL Developer extensions when running as an (additional) standard user on macOS. 

I've tested this successfully with an additional user named `sqldev` without administrator rights on my machine. Without this workaround I could not install any extension in SQL Developer.

## 1. Make sure you own the `sqldeveloper.app`

The `sqldeveloper.app` must be owned by the current user. If this is not the case or if you are unsure then download SQL Developer, extract the archive file and move it to a folder of your choice.

## 2. Start SQL Developer from command line 

Open a terminal window and run the commands described in the following stpes.

### 2.1 Determine your `JAVA_HOME`

```
/usr/libexec/java_home
```

in my case the result is 

```
/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home
```

### 2.2 Go to the `bin` directory of SQL Developer

Execute the next command in the terminal window, adjust the path before `SQLDeveloper.app` accordingly:

```
cd /Users/sqldev/Downloads/SQLDeveloper.app/Contents/Resources/sqldeveloper/sqldeveloper/bin
```

### 2.3 Start SQL Developer

Run this command in the terminal window to start SQL Developer:

```
./sqldeveloper
```

### 2.4 Enter the Path of your `JAVA_HOME`

SQL Developer will prompt you for the path of your `JAVA_HOME`. 

```
 Oracle SQL Developer
 Copyright (c) 2005, 2018, Oracle and/or its affiliates. All rights reserved.

/Users/sqldev/Downloads/SQLDeveloper.app/Contents/Resources/sqldeveloper/sqldeveloper/bin/../../ide/bin/launcher.sh: line 885: /usr/lib/exec/java_home: No such file or directory
Type the full pathname of a JDK installation (or Ctrl-C to quit), the path will be stored in /Users/sqldev/.sqldeveloper/19.2.1/product.conf
```

Enter result of step 1 here and press enter.

In my case this was `/Library/Java/JavaVirtualMachines/jdk-11.0.5.jdk/Contents/Home`.

## 3. Install Extensions

Now you can install utPLSQL for SQL Developer via `Help` -> `Check for Updates...` as you've done before. SQL Developer needs to be restarted to complete the process. 

## 4. Done

From now on you can start SQL Developer by double clicking on `sqldeveloper.app`. No need to do it via the terminal window. However, if you plan to update, install or uninstall extensions then you have to do that again as described above.

I hope you can now install utPLSQL for SQL Developer.

Please note that this issue is not directly related with utPLSQL. It's a flaw of the Oracle SQL Developer extension installation process and should be addressed by Oracle. Maybe you can post your findings in the [SQL Developer Forum](https://community.oracle.com/community/groundbreakers/database/developer-tools/sql_developer). Thank you.

**Comment by PhilippSalvisberg** [comment]
@itguyforautomation could you please give a feedback if the solution is working for you? Thank you.

**Comment by itguyforautomation** [comment]
Thanks very much for your assistance @PhilippSalvisberg , SQL developer tool works perfectly and able to run unit tests using utplsql.
